### ISSUE TITLE
Battery holder not available

### ISSUE THREAD

**Issue by ruslannovwork** [xreef/3D-Printed-modular-arm-and-components#1]
Hello,

I can't find the battery holder from https://mischianti.org/3d-printed-modular-holder-system-usb-rechargeable-lithium-battery-pack-5/
It is not available at 
https://github.com/xreef/3D-Printed-modular-arm-and-components/blob/master/BatteryHolder/18650BatteryHolder.stl

**Comment by xreef** [comment]
Hi,
please check the article on the site.
Bye Renzo
